development:
  adapter: postgresql
  encoding: unicode
  database: Recipe_Database
  pool: 5
  username: postgres
  password: new
  host: 127.0.0.1
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: Recipe_Database
  pool: 5
  username: postgres
  password: new
  host: 127.0.0.1
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: Recipe_Database
  pool: 5
  username: postgres
  password: new
  host: 127.0.0.1
  port: 5432
